export default {
  Home: 'HomeScreen',
  Login: 'LoginScreen',
  Register: 'RegisterScreen',
  Checkin: 'CheckinScreen',
  CheckinHistory: 'CheckinHistoryScreen',
  Account: 'AccountScreen',
  MainTab: 'TabNavigatorScreen',
  Splash: 'SplashScreen',
  TeacherList: 'TeacherListScreen',
  TopicList: 'TopicListScreen',
  TeacherDetail: 'TeacherDetailScreen',
  TopicDetail: 'TopicDetailScreen',
  UpdateAccount: 'UpdateAcountScreen',
  RegisterTopic: 'RegisterTopicScreen',
  ConversationList: 'ConversationListScreen',
  ConversationDetail: 'ConversationDetailScreen',
};
